### ISSUE TITLE
Enhance CI Pipeline with Sanity Check System for Meson Build Projects

### ISSUE THREAD

**Issue by dreamer-coding-555** [fossil-lib/fscl-xtool-c#18]
#### Summary
Request to enhance the current CI pipeline by adding a sanity check system to enforce best practices and validate critical elements such as hash values for wrap files and ensuring no `make` or `cmake` files are added. These checks will be implemented using Python scripts stored in the `.github/tools/` directory.

#### Details
- **Feature:** Add a sanity check system to the CI pipeline for Meson build projects.
- **Rationale:**
  - Ensures that all contributions adhere to established best practices, improving the overall quality and consistency of the project.
  - Automatically validates the integrity of wrap files by checking hash values, which is crucial for security and reliability.
  - Prevents the inclusion of unwanted build systems (`make` or `cmake`), maintaining the focus on Meson as the build system.
- **Implementation Considerations:**
  - **Sanity Checks to Include:**
    - **Hash Validation:** Verify that all wrap files have valid and correct hash values.
    - **File Checks:** Ensure no `make` or `cmake` files are included in the repository.
    - **Code Formatting:** Enforce consistent code formatting and styling rules.
    - **Dependency Management:** Validate that dependencies specified in `meson.build` are correctly formatted and necessary.
    - **Static Analysis:** Run static analysis tools to detect potential issues in the codebase.
  - **CI Integration:**
    - Integrate the sanity check system into the existing CI pipeline (e.g., GitHub Actions, GitLab CI, Jenkins).
    - Configure the CI to run these checks on every pull request and commit to the main branches.
    - Provide clear output and feedback from the sanity checks to assist developers in resolving any issues.
  - **Documentation:**
    - Update the contribution guidelines to include information about the sanity checks and how to run them locally.
    - Provide examples and instructions for addressing common sanity check failures.

#### Impact
- **Improved Code Quality:** Ensures all contributions meet a high standard of quality and adhere to best practices.
- **Enhanced Security:** Validates the integrity of wrap files, reducing the risk of tampering or errors.
- **Consistency:** Maintains the project’s focus on Meson by preventing the inclusion of `make` or `cmake` files.
- **Developer Experience:** Provides automated feedback to contributors, helping them catch and fix issues early in the development process.

#### Additional Information
- **References:**
  - [Meson Wrap System](https://mesonbuild.com/Wrap-dependency-system-manual.html)
  - [GitHub Actions Documentation](https://docs.github.com/en/actions)
  - [GitLab CI Documentation](https://docs.gitlab.com/ee/ci/)
  - [Jenkins Documentation](https://www.jenkins.io/doc/)

### Example Implementation Steps

1. **Create Sanity Check Scripts:**
   - Develop Python scripts to perform hash validation, file checks, and other sanity checks.
   - Example Python script for hash validation (`.github/tools/check_wrap_hashes.py`):
     ```python
     import subprocess
     import os

     def verify_wrap_files():
         wrap_files = []
         for root, dirs, files in os.walk('subprojects'):
             for file in files:
                 if file.endswith('.wrap'):
                     wrap_files.append(os.path.join(root, file))

         for wrap in wrap_files:
             result = subprocess.run(['meson', 'wrap', 'verify', wrap], capture_output=True, text=True)
             if result.returncode != 0:
                 print(f"Invalid hash in {wrap}")
                 print(result.stdout)
                 exit(1)

     if __name__ == "__main__":
         verify_wrap_files()
     ```

2. **Integrate into CI Pipeline:**
   - Add steps in the CI configuration file (e.g., `.github/workflows/ci.yml` for GitHub Actions) to run the sanity check scripts.
   - Example CI configuration:
     ```yaml
     name: CI

     on: [push, pull_request]

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - name: Set up Python
             uses: actions/setup-python@v2
             with:
               python-version: '3.x'
           - name: Install Meson
             run: |
               python -m pip install meson
           - name: Run Sanity Checks
             run: |
               python .github/tools/check_wrap_hashes.py
               python .github/tools/check_no_make_cmake_files.py
           - name: Build Project
             run: |
               meson setup build
               meson compile -C build
     ```

3. **Create Additional Sanity Check Scripts:**
   - Example Python script to ensure no `make` or `cmake` files are added (`.github/tools/check_no_make_cmake_files.py`):
     ```python
     import os

     def check_for_unwanted_files():
         for root, dirs, files in os.walk('.'):
             for file in files:
                 if file in ['Makefile', 'CMakeLists.txt'] or file.endswith('.cmake'):
                     print(f"Unwanted file found: {os.path.join(root, file)}")
                     exit(1)

     if __name__ == "__main__":
         check_for_unwanted_files()
     ```

4. **Update Documentation:**
   - Add a section in the contribution guidelines about the sanity check system.
   - Provide instructions on how to run the sanity checks locally before pushing changes.

By implementing this feature, we can ensure that the Meson build projects maintain high standards of quality and security, making the development process smoother and more reliable for all contributors.
